name: 'sypos-workspace'
services:
  workspace-db-pg:
    build:
      dockerfile: ../../docker/images/postgres.dockerfile
    container_name: workspace-pg
    env_file:
      - ./.env.local
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
